/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team4.JavafxInterf;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.mindrot.jbcrypt.BCrypt;

import edu.duke.ece651.team4.shared.UserDAO;
import edu.duke.ece651.team4.shared.UserDAOImpl;
import edu.duke.ece651.team4.shared.User;

// import edu.duke.ece651.team4.TrackerServer.TrackerServerApplication;
// import edu.duke.ece651.team4.TrackerServer.entity.*;
// import edu.duke.ece651.team4.TrackerServer.service.*;
// import org.mindrot.jbcrypt.BCrypt;
// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.boot.test.context.SpringBootTest;

// @SpringBootTest(classes = {TrackerServerApplication.class})
class AppTest {
    // @Autowired
    // private StuController StuController;

    @Test 
    public void appHasAGreeting() {
        // App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        // User admin_basic = new User("admin", "admin", "admin", "admin", BCrypt.hashpw("test", BCrypt.gensalt(12)), "admin", "admin@admin.com");
        // User student_basic = new User("student", "student", "student", "student", BCrypt.hashpw("test", BCrypt.gensalt(12)), "student", "student@student.com");
        // StuController.addUser("admin", "admin", "admin", "admin", LoginManager.hashPassword("test"), "admin", "admin@admin.com");
        String res = LoginManager.hashPassword("123456");
        System.out.println(res);
        StuController.addUser("admin", "admin", "admin", "admin", "test", "admin", "admin@admin.com");
        StuController.addUser("prof01", "prof", "prof", "01", "test", "professor", "professor@prof.com");
        StuController.addUser("stu01", "stu", "stu", "stu", "test", "student", "stu@stu.com");
        StuController.addUser("stu02", "stu2", "stu2", "stu2", "test", "student", "stu2@stus.com");
        CourseController.addCourse("ECE651", "sys");
        CourseController.addCourse("ECE650", "ysy");
        SectionController.addSection("ECE651S2", "ECE651", "prof01");
        SectionController.addSection("ECE651S1", "ECE651", "prof01");
        SectionController.addSection("ECE650S1", "ECE650", "prof01");
        StuController.addStudentToSection("stu01", "ECE651S1");
        StuController.addStudentToSection("stu02", "ECE651S1");
        StuController.addStudentToSection("stu01", "ECE651S2");

        // StuController.addUser("")
      }

    // @Test
    // public void testPSW(){
    //     String password = "testpassword";
    //     String hashed = LoginManager.hashPassword(password);
    //     UserDAO helper = new UserDAOImpl();

    //     User user = helper.getUser("testadmin4");

    //     System.out.println("Hashed: " + hashed);
    //     System.out.println("Check: " + BCrypt.checkpw("testpassword", hashed));
    //     System.out.println("type: " + hashed.getClass().getName());
    //     assertEquals(hashed.length(), user.password.length());
    //     assertTrue(BCrypt.checkpw("testpassword", "$2a$12$ynHaQ3d5ZFclA.PkmVuIveaz5O4JvFTVVi4hs9.RHrnqU5TQ0BQS."));
    //     // assertTrue(BCrypt.checkpw("123456", user.password));
    // }
}
