/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team4.client;

import java.io.BufferedReader;
import java.io.InputStreamReader;

//import edu.duke.ece651.team4.shared.MyName;

public class App {
  // public String getMessage() {
  // return "Hello from the client for "+ MyName.getName();
  // }
  public static void main(String[] args) {
    // App a = new App();
    Client client = new Client("localhost", 12345);
    try {
      client.startClient();
      BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
      String userInput;
      String serverInput;

      if ((serverInput = client.in.readLine()) != null) {
        System.out.println(serverInput);
      }

      while (true) {
        if (stdIn.ready()) { // Check if user input is available
          userInput = stdIn.readLine();
          client.out.println(userInput);
        }
        if (client.in.ready()) { // Check if server message is available
          serverInput = client.in.readLine();
          System.out.println(serverInput);
          // Break if a certain message is received from server
          // if (serverInput.equals("some condition to exit")) break;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        client.stopClient();
      } catch (Exception e) {
        e.printStackTrace();
      }
    }
  }
}
